version: '3.9'

services:
  app:
    build:
      context: .
    command: bash start.sh
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      MAVEN_OPTS: "-Dmaven.repo.local=/box"
    volumes:
      - .:/reactive-flashcards
      - box:/box
    depends_on:
      - db
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: reactive-flashcards
      MONGO_INITDB_ROOT_PASSWORD: reactive-flashcards
      MONGO_INITDB_DATABASE: reactive-flashcards
    ports:
      - "27017:27017"
  box:
    image: busybox # Cache das dependências
    volumes:
      - /box
volumes:
  db:
  box: